# Generated by Django 3.1.6 on 2021-06-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0005_receivedmessages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedmessages',
            name='phonenumber',
            field=models.CharField(max_length=50),
        ),
    ]
