# Generated by Django 3.1.6 on 2021-06-11 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0006_auto_20210611_0633'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReceivedMessages',
        ),
    ]
