# Generated by Django 3.1.6 on 2021-06-10 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0002_messages_sent_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='sent_date',
        ),
    ]
